feat: Add `mintToTreasury` BTT tests (SC-392)
marsfoundation/sparklend-testing pull request #18
Opened 2024-04-17 14:57 UTC by lucas-manuel

2024-04-25 16:48 UTC, barrutko submitted a review, later dismissed

2024-05-02 10:10 UTC, hexonaut commented
Needs to be synced up with `master`.

2024-05-03 06:45 UTC, hexonaut requested changes
Mostly looks good. I like the prove no-op thing.

2024-05-03 06:45 UTC, hexonaut commented on test/MintToTreasury.tree
> +pool.mintToTreasury()
Missing revert case where `amount == 1` and the mint amount is zero because of the scaling rounding. `ScaledBalanceTokenBase:L73`.

2024-05-03 06:45 UTC, hexonaut commented on test/MintToTreasury.t.sol
> +        ( uint256 scaledAccruedToTreasury, uint256 liquidityIndex2, uint256 supplierYield )
This should be `liquidityIndex` without the 2?

2024-05-20 09:44 UTC, barrutko commented on test/MintToTreasury.tree
> +pool.mintToTreasury()
Was this addressed?

2024-05-28 23:18 UTC, hexonaut approved these changes

2024-05-29 22:50 UTC, barrutko approved these changes

2024-05-30 11:29 UTC, merged