fix: Update to use non-zero `reserveFactor` (SC-404)
marsfoundation/sparklend-testing pull request #20
Opened 2024-04-22 15:21 UTC by lucas-manuel

2024-04-26 14:41 UTC, barrutko requested changes

2024-04-26 14:41 UTC, barrutko commented on test/FlashLoan.t.sol
> +            accruedToTreasury:         0,
```suggestion
            accruedToTreasury:         0,
```

2024-04-26 14:41 UTC, barrutko commented on test/FlashLoanSimple.t.sol
> +        poolParams.currentLiquidityRate      = liquidityRate + 2;  // Rounding
```suggestion
        poolParams.currentLiquidityRate      = liquidityRate + 2;  // Rounding
```

2024-04-26 14:41 UTC, barrutko commented on test/FlashLoanSimple.t.sol
>          poolParams.currentVariableBorrowRate = borrowRate + 1;  // Rounding
```suggestion
        poolParams.currentLiquidityRate      = liquidityRate + 2;  // Rounding
        poolParams.currentVariableBorrowRate = borrowRate + 1;     // Rounding
```

2024-04-26 14:41 UTC, barrutko commented on test/RepayWithATokens.t.sol
> +            currentLiquidityRate:      0.0296875e27,  // 3.125% * 95%
```suggestion
            currentLiquidityRate:      0.0296875e27,  // 3.125% * 95%
```

2024-04-26 14:41 UTC, barrutko commented on test/RepayWithATokens.t.sol
> +            currentLiquidityRate:      0.0296875e27,  // 3.125% * 95%
There might be more of that
```suggestion
            currentLiquidityRate:      0.0296875e27,  // 3.125% * 95%
```

2024-04-26 14:41 UTC, barrutko commented on test/RepayWithATokens.t.sol
> +        assertEq(liquidityRate, 0.000000000000000000000095000e27);  // 1 / 499.999902325764663556e18 = 2e-21 => 2e-21 * (0.05e27 + 5e4) = 1e5 in ray (rounding) TODO: Investigate why not 95%
Is it not 95%?

2024-04-26 14:41 UTC, barrutko commented on test/RepayWithATokens.t.sol
> +        poolParams.currentVariableBorrowRate = borrowRate;
```suggestion
        poolParams.currentVariableBorrowRate = borrowRate;
```

2024-04-26 14:41 UTC, barrutko commented on test/Withdraw.t.sol
> +        assertEq(borrowRate,    0.0525e27);          // 5% + 10%/80% of 2% = 5.25%
Too many spaces

2024-04-30 13:40 UTC, lucas-manuel commented on test/Borrow.t.sol
> +        poolParams.currentVariableBorrowRate = 0.0625e27;          // 50% utilized: 5% + 50%/80% * 2% = 6.25%TIL
Yeah cool right?

2024-04-30 13:42 UTC, lucas-manuel commented on test/Borrow.t.sol
> +        poolParams.currentVariableBorrowRate = 0.0625e27;          // 50% utilized: 5% + 50%/80% * 2% = 6.25%TIL
Removed

2024-04-30 13:43 UTC, lucas-manuel commented on test/Borrow.t.sol
> +        poolParams.currentLiquidityRate      = 0.03125e27 * 0.95;  // 50% utilized: 6.25% * 50% = 3.125% * (1 - reserveFactor)
Yeah fair I'll make this change everywhere

2024-04-30 13:48 UTC, lucas-manuel commented on test/FlashLoan.t.sol
> +        assertLt(liquidityRate, 0.0049875e27);   // 5.25% * 95%
Good catch, fixed

2024-04-30 13:49 UTC, lucas-manuel commented on test/FlashLoan.t.sol
> +            accruedToTreasury:         0,
Fixed

2024-04-30 13:51 UTC, lucas-manuel commented on test/FlashLoanSimple.t.sol
> +        poolParams.currentLiquidityRate      = liquidityRate + 2;  // Rounding
Think whitespace is gone now, forgot I turned off trim whitespace setting

2024-04-30 13:51 UTC, lucas-manuel commented on test/FlashLoanSimple.t.sol
>          poolParams.currentVariableBorrowRate = borrowRate + 1;  // Rounding
Fixed

2024-04-30 13:52 UTC, lucas-manuel commented on test/RepayWithATokens.t.sol
> +        assertEq(liquidityRate, 0.000000000000000000000095000e27);  // 1 / 499.999902325764663556e18 = 2e-21 => 2e-21 * (0.05e27 + 5e4) = 1e5 in ray (rounding) TODO: Investigate why not 95%
Yeah you're right removed

2024-04-30 13:52 UTC, lucas-manuel commented on test/RepayWithATokens.t.sol
> +        poolParams.currentVariableBorrowRate = borrowRate;
Fixed

2024-04-30 13:53 UTC, lucas-manuel commented on test/Withdraw.t.sol
> +        assertEq(borrowRate,    0.0525e27);          // 5% + 10%/80% of 2% = 5.25%
Fixed

2024-04-30 14:53 UTC, barrutko approved these changes
Updated version looks good. I'll reapprove once up to date with master.

2024-05-16 06:45 UTC, hexonaut submitted a review, later dismissed
One minor thing then LGTM.

2024-05-16 06:45 UTC, hexonaut commented on test/Borrow.t.sol
> +        poolParams.currentLiquidityRate      = 0.03125e27 * 0.95;  // 50% utilized: 6.25% * 50% *  * (1 - reserveFactor) = 3.125% * 95%
Two multiplications in the comment. `50% *  * (1 - reserveFactor)` should be `50% * (1 - reserveFactor)`

2024-05-16 11:02 UTC, barrutko submitted a review, later dismissed

2024-05-16 13:58 UTC, barrutko approved these changes

2024-05-17 08:18 UTC, hexonaut approved these changes

2024-05-17 13:57 UTC, merged