feat: Add Pool ACL tests (SC-403)
marsfoundation/sparklend-testing pull request #21
Opened 2024-04-23 15:21 UTC by lucas-manuel

2024-04-25 16:57 UTC, barrutko requested changes
Not sure if that falls into the scope of that PR, but I miss sanity checks that the state actually changes when called by a proper address. I.e. after successfully calling `configureEModeCategory` I'd expect a simple sanity check that the config of a given EMode category changed. But maybe this should be tested in PoolConfigurator and here testing exclusively the access is ok. Im'm open to discussion.

2024-04-25 17:35 UTC, lucas-manuel commented
@barrutko Yeah I opted to do ACL testing first here in isolation to make sure that its covered across the whole protocol. The state assertions for non-setter ACL functions would've made the scope too large so I decided to put them all here first. Open to discussion as well, just thought this would be a good measure for us to take to make sure our bases were covered with this critical functionality first.

2024-04-26 14:44 UTC, barrutko submitted a review, later dismissed
Yeah, this sounds reasonable to me, as long these end up being tested somewhere sometime anyway.

Smaller PR = ❤️

2024-04-30 07:41 UTC, hexonaut commented on test/ACL.t.sol
> +    // TODO: Investigate this.
What is meant by this? The `upgradeToAndCall` works fine in the test code, and it appears in both the deployed proxy and repo.

2024-04-30 13:35 UTC, barrutko approved these changes

2024-04-30 14:29 UTC, hexonaut approved these changes

2024-04-30 14:34 UTC, merged