feat: Add PoolAddressesProvider, Registry, and ACLManager ACL tests (SC-409)
marsfoundation/sparklend-testing pull request #23
Opened 2024-04-25 16:35 UTC by lucas-manuel

2024-04-30 08:16 UTC, hexonaut requested changes
Should be SC-411 in the title, and two missing functions.

2024-04-30 08:16 UTC, hexonaut commented on test/ACL.t.sol
> +
Missing `setPoolImpl` and `setPoolConfiguratorImpl`

2024-04-30 14:34 UTC, hexonaut approved these changes

2024-05-02 10:04 UTC, hexonaut approved these changes

2024-05-07 18:59 UTC, barrutko approved these changes

2024-05-07 19:02 UTC, merged